-- CREATE DATABASE CODEBOX;
USE CODEBOX;
CREATE TABLE POP(
    ID_EMPO INT,
    NMAE_EMPO VARCHAR(255),
    CITY VARCHAR (255)
);
INSERT into pop(ID_EMPO,NMAE_EMPO,CITY)
VALUES(3230344,'BOBO','CAIRO');
-- SELECT * from POP;
INSERT into pop(ID_EMPO,NMAE_EMPO,CITY)
VALUES(3230345,'OBO','AIRO');
SELECT * from POP;
